# Generated by Django 4.2.13 on 2024-07-09 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_change_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
