# Generated by Django 4.2.13 on 2024-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_last_change_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client', 'service'], name='services_su_client__f485a9_idx'),
        ),
    ]
